blog_app/urls.py
from django.urls import path,include
from . import views

app_name = 'blog_app'

urlpatterns = [
    path('',views.index.as_view(), name = 'index'),
    path('post_create', views.PostCreate.as_view(),name = 'post_create'),
    path('post_detail/<int:pk>', views.PostDetail.as_view(),name = 'post_detail'),
    path('post_update/<int:pk>',views.PostUpdate.as_view(),name = 'post_update'),
    path('post_damage/<int:pk>',views.PostDelete.as_view(),name = 'post_delete'),
    path('post_list',views.PostList.as_view(),name ='post_list'),
    path('login',views.Login.as_view(),name ='login'),
    path('logout',views.Logout.as_view(),name ='logout'),
    path('signup',views.SignUp.as_view(),name ='signup'),
    path('like/<int:post_id>',views.Like_add,name ='like_add'),
    path('category_list',views.CategoryList.as_view(),name ='category_list'),
    path('subcategory_list',views.SubCategoryList.as_view(),name ='subcategory_list'),
    path('ategory_detail/<str:name_en>',views.CategoryDetail.as_view(),name ='category_detail'),
    path('search',views.Search,name='search'),#searchのpathを追加
    ]

myproject/urls.py
from django.contrib import admin 
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog_app.urls'))
]

#画像urlを処理
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField('カテゴリ名',max_length=50)
    name_en = models.CharField('カテゴリ名英語',max_length=10)
    created_at = models.DateTimeField( auto_now_add = True)
    updated_at = models.DateTimeField( auto_now=True)
    
    def post_count(self):
        n = Post.objects.filter(category = self).count()
        return n

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField('サブカテゴリ名',max_length=50)
    name_en = models.CharField('サブカテゴリ名英語',max_length=10)
    created_at = models.DateTimeField( auto_now_add = True)
    updated_at = models.DateTimeField( auto_now=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, blank=False)
    title = models.CharField("タイトル", max_length=50)
    content = models.TextField("内容", max_length=1000)
    category = models.ForeignKey('Category',on_delete=models.PROTECT)
    thumbnail = models.ImageField(upload_to='images/',blank=True)
    subcategory = models.ForeignKey('SubCategory',on_delete=models.PROTECT)
    created_at = models.DateTimeField( auto_now_add = True)
    updated_at = models.DateTimeField( auto_now=True)

    def __str__(self):
        return self.title

class Like(models.Model):
    post = models.ForeignKey(Post, verbose_name="投稿", on_delete=models.PROTECT)#自分のlike
    user = models.ForeignKey(User, verbose_name="Likeしたユーザー", on_delete=models.PROTECT)#他人のlike

blog_app/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ('title','content','category','subcategory','thumbnail')

  def  __init__(self,*args,**kwargs):
      super().__init__(*args,**kwargs)
      for field in self.fields.values():
          field.widget.attrs['class'] = 'form-control'

class LoginForm(AuthenticationForm):
  #レイアウトをきれいにする
  def  __init__(self,*args,**kwargs):
      super().__init__(*args,**kwargs)
      for field in self.fields.values():
          field.widget.attrs['class'] = 'form-control'

class SignUpForm(UserCreationForm):
   class Meta:
     model = User
     fields = ('username','email','password1','password2')

     #レイアウトをきれいにする
     def  __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

#検索バーを作成
class SearchForm(forms.Form):
   freeword = forms.CharField(min_length=1,max_length=30,label='',required=False)

   def __init__(self,*args,**kwargs):
     super().__init__(*args,**kwargs)

blog_app/views.py
from django.shortcuts import render,resolve_url,redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView,CreateView,DetailView,UpdateView,DeleteView,ListView
from .models import Post,Like,Category,SubCategory
from django.urls import reverse_lazy
from .forms import PostForm,LoginForm,SignUpForm,SearchForm #SearchFormを追加
from django.contrib import messages
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin 
from django.contrib.auth.decorators import login_required
from django.db.models import Q 
from django.core.paginator import Paginator #paginatorを追加する

class OnlyMyPostMixin(UserPassesTestMixin):
  raise_exception = True
  def test_func(self):
    post = Post.objects.get(id = self.kwargs['pk'])
    return post.author == self.request.user


class index(TemplateView):
  template_name = 'blog_app/index.html'

  def get_context_data(self,*args, **kwargs):
      context = super().get_context_data(**kwargs)
      post_list = Post.objects.all().order_by('-created_at')
      context = {
        'post_list': post_list,
      }
      return context

class PostCreate(LoginRequiredMixin,CreateView):
  model = Post
  form_class = PostForm
  success_url = reverse_lazy('blog_app:index')
  def form_valid(self, form):
    form.instance.author_id = self.request.user.id
    return super(PostCreate,self).form_valid(form)

  def get_success_url(self):
    messages.success(self.request,'100esを登録しました。')
    return resolve_url('blog_app:index')

class PostDetail(DetailView):
  model = Post

  def get_context_data(self, *args,**kwargs):
      detail_data  = Post.objects.get(id=self.kwargs['pk'])
      category_posts = Post.objects.filter(category = detail_data.category).order_by('-created_at')[:5]
      params = {
        'object':detail_data,
        'category_posts':category_posts,
      }
      return params


class PostUpdate(OnlyMyPostMixin,UpdateView):
  model = Post
  form_class = PostForm

  def get_success_url(self):
    messages.info(self.request, '100esを更新しました。')
    return resolve_url('blog_app:post_detail',pk=self.kwargs['pk'])

class PostDelete(OnlyMyPostMixin,DeleteView):
  model = Post
  def get_success_url(self):
    messages.info(self.request, '100esを削除しました')
    return resolve_url('blog_app:index')

class PostList(ListView):
  model = Post
  #5件ごとにページを切り替える
  paginate_by = 5
  def get_queryset(self):
    return Post.objects.all().order_by('-created_at')

class Login(LoginView):
   form_class = LoginForm
   template_name = 'blog_app/login.html'

class Logout(LogoutView):
  template_name = 'blog_app/logout.html'

class SignUp(CreateView):
  form_class = SignUpForm
  template_name = 'blog_app/signup.html'
  success_url = reverse_lazy('blog_app:index')

  def form_valid(self, form):
    user = form.save()
    login(self.request,user)
    self.object = user
    messages.info(self.request,'ユーザー登録をしました。')
    return HttpResponseRedirect(self.get_success_url())

@login_required
def Like_add(request,post_id):
    post = Post.objects.get(id = post_id)
    is_liked = Like.objects.filter(user = request.user,post = post_id).count()
    if is_liked > 0:
      messages.info(request, 'すでにお気に入りに追加済みです。')
      return redirect('blog_app:post_detail', post.id)
    like = Like()
    like.user = request.user
    like.post = post
    like.save()

    messages.success(request, 'お気に入りに追加しました')
    return redirect('blog_app:post_detail', post.id)

class CategoryList(ListView):
  model = Category

class SubCategoryList(ListView):
  model = SubCategory

class CategoryDetail(DetailView):
  model = Category
  slug_field = 'name_en'
  slug_url_kwarg = 'name_en'

  def get_context_data(self,*args, **kwargs):
    detail_data = Category.objects.get(name_en = self.kwargs['name_en'])
    category_posts = Post.objects.filter(category = detail_data.id).order_by('-created_at')

    params = {
      'object':detail_data,
      'category_posts':category_posts,
    }

    return params

#クエスチョンのQ
def Search(request):
  if request.method == 'POST':
    searchform = SearchForm(request.POST)

    if searchform.is_valid():
      freeword = searchform.cleaned_data['freeword']
      search_list = Post.objects.filter(Q(title__icontains = freeword)|Q(content__icontains = freeword))

    params = {
       'search_list':search_list,
     }

    return render (request, 'blog_app/search.html',params) #クエスチョンのQ

blog_app/templates/blog_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{{request.site.siteconfig.meta_title}}</title>
    <!-- MDB icon -->
    <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
      rel="stylesheet"
    />
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <button
            class="navbar-toggler"
            type="button"
            data-mdb-toggle="collapse"
            data-mdb-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <!--Homeリンク -->
            <a class="navbar-brand" href="{% url 'blog_app:index' %}"
              ><i class="fas fa-home"></i>100story</a
            >
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              <!-- Life stageで見る -->
              <div class="btn-group shadow-0">
                <button
                  type="button"
                  class="btn btn-light dropdown-toggle"
                  data-mdb-toggle="dropdown"
                  aria-expanded="false"
                >
                  <i class="fas fa-edit"></i> Life stage別で見る
                </button>
                <ul class="dropdown-menu">
                  {% for item in category_list%}
                  <li>
                    <a
                      class="dropdown-item"
                      href="{% url 'blog_app:category_detail' item.name_en %}"
                      >{{item.name}}</a
                    >
                  </li>
                  {% endfor %}
                  <hr />
                  <li>
                    <a
                      class="dropdown-item"
                      href="{% url 'blog_app:category_list' %}"
                      >Life Stage一覧</a
                    >
                  </li>
                </ul>
              </div>
              <!-- Life stageで見る-->

              <!-- post -->
              <div class="btn-group shadow-0">
                <button
                  type="button"
                  class="btn btn-light dropdown-toggle"
                  data-mdb-toggle="dropdown"
                  aria-expanded="false"
                >
                  <i class="fas fa-edit"></i> post
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <a
                      class="dropdown-item"
                      href="{% url 'blog_app:post_create' %}"
                      >投稿する</a
                    >
                  </li>
                  <li>
                    <a
                      class="dropdown-item"
                      href="{% url 'blog_app:post_list' %}"
                      >投稿の作成日を見る</a
                    >
                  </li>
                </ul>
              </div>
              <!-- post -->

              <!-- account -->
              <div class="btn-group shadow-0">
                <button
                  type="button"
                  class="btn btn-light dropdown-toggle"
                  data-mdb-toggle="dropdown"
                  aria-expanded="false"
                >
                  <i class="fas fa-user"></i> account
                </button>
                <ul class="dropdown-menu">
                  {% if request.user.is_authenticated %}
                  <li><a class="dropdown-item">{{request.user}}</a></li>
                  <li>
                    <a class="dropdown-item" href="{% url 'blog_app:logout' %}"
                      >ログアウト</a
                    >
                  </li>
                  <li><a class="dropdown-item" href="/admin">Django管理</a></li>
                  {% else %}
                  <li>
                    <a class="dropdown-item" href="{% url 'blog_app:login' %}"
                      >ログイン</a
                    >
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'blog_app:signup' %}"
                      >ユーザー登録</a
                    >
                  </li>
                  {% endif %}
                </ul>
              </div>
            </ul>
            <!-- search -->
            <form
              action="{% url 'blog_app:search'%}"
              class="d-flex input-group w-auto"
              method="POST"
            >
              {% csrf_token %}
              <input
                type="search"
                class="form-control"
                placeholder="タイトル名、内容"
                aria-label="Search"
                name="freeword"
              />
              <button
                class="btn btn-outline-primary"
                type="submit"
                data-mdb-ripple-color="dark"
              >
                Search
              </button>
            </form>
          </div>
        </div>
      </nav>
      <!-- Navbar -->
    </header>
    <!-- /header  -->

    <!-- main  -->
    <main class="container">
      {% if messages %} {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">
        {{ message }}
      </div>
      {% endfor %} {% endif %} {% block content %} {% endblock %}
    </main>
    <!-- /main  -->

    <!-- footer -->
    <footer class="text-center text-white" style="background-color: #f1f1f1">
      <!-- Grid container -->
      <div class="container pt-4">
        <!-- Section: Social media -->
        <section class="mb-4">
          <!-- Facebook -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.facebook.com/profile.php?id=100025204331992"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-facebook-f"></i
          ></a>

          <!-- Linkedin -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.linkedin.com/in/%E8%A1%B7-%E5%B4%8E%E5%B1%B1%E3%80%80-365100206/"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-linkedin"></i
          ></a>
          <!-- Github -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://github.com/SakiyamaKanau"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-github"></i
          ></a>
        </section>
        <!-- Section: Social media -->
      </div>
      <!-- Grid container -->

      <!-- Copyright -->
      <div
        class="text-center text-dark p-3"
        style="background-color: rgba(0, 0, 0, 0.2)"
      >
        © 2021 Copyright:SAKIYAMA KANAU
      </div>
      <!-- Copyright -->
    </footer>
    <!-- /footer -->

    <!-- MDB -->
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
    ></script>
    <!-- Custom scripts -->
    <script type="text/javascript"></script>
  </body>
</html>

blog_app/templates/blog_app/category_detail.html
{%extends 'blog_app/base.html' %} {% block content %}
<div class="row">
  <div class="col-md-6">

      <br />
      <h2>{{object.name}}</h2>
      <hr />
      <ul class="list-group">
         {% for item in category_posts %}
         <li class = "list-group-item"><a href="{% url 'blog_app:post_detail' item.id %}">{{ item.title }}</a></i>
         {% endfor %}
      </ul>
  </div>

    {% endblock %}

blog_app/templates/blog_app/category_list.html
{%extends 'blog_app/base.html' %} {% block content %}
<div class="row">
  <div class="col-md-9">
    <br>
      <h2>Life stage</h2>
    <br>
  </div>
</div>

<div class="row">

    {% for category in category_list %}
      <div class = "col-md-4">
       <br>
       <div class = "card" >
         <div class= "card-body">
              <h4 class = "card-title">
                <a style = "color:black" href="{% url 'blog_app:category_detail' category.name_en %}">{{ category.name }}</a><small>({{category.post_count}})</small>
              </h4>
              <a href="{% url 'blog_app:category_detail' category.name_en %}"><small>全て見る</small></a>
            <hr>
            {% for post in category.post_set.all|slice:":5" %}
            <p><a href = "{% url 'blog_app:post_detail' post.id%}">{{post.title}}</a></p>
            {% endfor %}
          </div>
        </div>
      </div>
    {% endfor %}

 </div>
 <br> 
{% endblock %}

blog_app/templates/blog_app/index.html
{% extends 'blog_app/base.html' %} {% block content %}

<!-- スライダー -->
<div class="p-5 text-center bg-light">
  <div
    id="carouselExampleControls"
    class="carousel slide"
    data-mdb-ride="carousel"
  >
    <div class="carousel-inner">
      <div class="carousel-item active">
        <h1 class="mb-3">One hand read story</h1>
        <h4 class="mb-3">100times,100hours,100km...</h4>
      </div>
      <div class="carousel-item">
        <h1 class="mb-3">100にまつわる</h1>
        <h4 class="mb-3">エピソードを集めました</h4>
      </div>
    </div>
    <button
      class="carousel-control-prev"
      type="button"
      data-mdb-target="#carouselExampleControls"
      data-mdb-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button
      class="carousel-control-next"
      type="button"
      data-mdb-target="#carouselExampleControls"
      data-mdb-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div></div>
</div>

<!-- カードボタン -->
<div class="row row-cols-2 row-cols-md-4 g-3">
  {% for item in post_list %}
  <div class="col">
    <button id="primary" class="btn btn-light" >
      <!--img条件分岐 -->
      <div class="card h-100">
        {% if item.thumbnail %}
        <a href="{% url 'blog_app:post_detail' item.id %}">
          <img
            src="{{ item.thumbnail.url}}"
            class="card-img-top"
            alt="{{item.title}}"
          />
        </a>
        {% else %}
        <a href="{% url 'blog_app:post_detail' item.id %}">
          <img
            src="https://mdbootstrap.com/img/new/standard/city/041.jpg"
            class="card-img-top"
            alt="{{item.title}}"
          />
        </a>
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ item.title }}</h5>
          <!-- text-->
          <p class="card-text">{{item.content|safe|truncatechars_html:12}}</p><!-- contentの12文字目までを反映-->
          <hr />
          <!-- カテゴリ、サブカテゴリ-->
          <small>{{item.category}}</small>
          <small>/{{item.subcategory}}</small>
          <a href="{% url 'blog_app:post_detail' item.id %}"></a>
        </div>
      </div>
    </button>
  </div>
  {% endfor %}
</div>

{% endblock%}

blog_app/templates/blog_app/login.html
<head>

<head>

{%extends 'blog_app/base.html' %} {% block content %}
<div class="row">
  <div class="col-md-6">
      <br />
      <h2>Sign in</h2>
      <br />
      <!-- /loginform作成 -->
      <form action="" method="post">
        {% csrf_token %} {{form.non_field_errors}} {% for field in form%}
        {{field.label}} {{ field}} {{ field.errors}}
        <br />
        {% endfor%}
        <button type="submit" class="btn btn-light btn-rounded">Login</button>
      </form>
      <p> Don't have an account <a href="{% url 'blog_app:signup' %}" type="button" class="btn btn-link" data-mdb-ripple-color="dark">sign up here</a> </p>
   </div>

    {% endblock %}

blog_app/templates/blog_app/logout.html
{%extends 'blog_app/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-6">
    <br>
    <h2>Logout</h2>
    <br>
    <p>ログアウトしました</p>
  </div>
  {% endblock%}

blog_app/templates/blog_app/pagination.html
<!-- ページネーション -->
<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>
<!-- ページネーション -->

blog_app/templates/blog_app/post_confirm_delete.html
{%extends 'blog_app/base.html' %} {% block content %}
<div class="row">
  <div class="col-md-9">
    <br />
    <h2>100story削除</h2>
    <br />

    <div class="alert alert-danger" role="alert">
      <form method="post">
        {% csrf_token %}
        <p>以下の内容を本当に削除しますか?</p>
        <input type="submit" class="btn btn-danger" value="削除する" />
      </form>
    </div>
    <br />
  </div>

    <!-- 投稿img -->
  <div class="col-md-4">
    <br />
    <br />
    <div class="card">
      <div class="bg-image">
        <img src="https://mdbootstrap.com/img/new/standard/city/053.jpg" class="img-fluid" alt="Sample" />
        <div class="mask" style="background-color: rgba(0, 0, 0, 0.6)">
          <div class="d-flex justify-content-center align-items-center h-100">
            <p class="text-white mb-0">{{object.title}}</p>
          </div>
        </div>
      </div>
    </div>
    <br />
    <br />
  </div>

  <!-- 投稿内容 -->
  <div class="col-md-4">
    <br />
    <br />
    <div class="card" style="width: 30rem">
      <div class="card-body">
        <p class="card-text">{{object.content}}</p>
        <p class="text-end">{{object.content|length}}/100</p>
      </div>
    </div>
    <br />
    <br />
  </div>
</div>
{% endblock%}

blog_app/templates/blog_app/post_detail.html
{% extends 'blog_app/base.html' %} {% block content %}

<div class="row">
  <br />
  
  <!-- 投稿img -->
  <div class="col-md-3">
    <br />
    <br />
    <div class="card">
      <div class="bg-image">
        <!--img条件分岐 -->
        {% if object.thumbnail%}
        <img src="{{ object.thumbnail.url }}" class="img-fluid" alt="{{object.title}}" />
        {% else %}
        <img src="https://mdbootstrap.com/img/new/standard/city/053.jpg" class="img-fluid" alt="Sample" />
        {% endif %}
      </div>
    </div>
    <br />
    <br />
    <!-- 戻るボタンを追加 -->
    <a href = "javascript:void(0);" onclick="window.history.back();" class="btn btn-outline-dark">戻る</a>
    
    <br />
    <br />
  </div>
  
  <!-- 投稿内容 -->
  <div class="col-md-6">
    <br />
    <br />
    <div class="card">

      <div class="card-body">
        <!-- 内容 改行safe-->
        <p class="card-text">{{object.content|safe | linebreaksbr | urlize}}</p> <!-- linebreaksbrで改行safe-->
        <!-- お気に入りボタン-->
        <a href="{% url 'blog_app:like_add' object.pk %}"type="button" class="btn btn-danger btn-floating">
          <i class="far fa-heart"></i>
        </a>

        <hr>
        <!-- 編集/削除ボタン-->
        {% if object.author == request.user %}
        <a href="{% url 'blog_app:post_update' object.id %}" type="button" class="btn btn-info btn-rounded">
          <i class="fas fa-pen"></i>
        </a>
        <a href="{% url 'blog_app:post_delete' object.id %}" type="button" class="btn btn-danger btn-rounded">
          <i class="fas fa-trash" type="button"></i>
        </a>
        {% endif %}
      </div>
    </div>
    <br />
    <br />
  </div>
<!-- サイドバー -->
<div class="col-md-3">
　
  <h5 class="card-title">”{{object.category}}” 関連</h5>
  <ol class="list-group list-group-numbered">
    {% for item in category_posts%}
      <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
         {% comment %} <div class="fw-bold"><a href="{% url 'blog_app:post_detail' item.id %}">{{item.title}}</a></div> {% endcomment %}
        </div>
      </li>
    {% endfor %}
  </ol>
</div>

</div>

{% endblock%}

blog_app/templates/blog_app/post_form.html
{%extends 'blog_app/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-9">
    <br>
    <h2>100story投稿</h2>
    <br>
    <!-- enctype="multipart/form-data" -->
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- タイトルを追加 -->
      <div class="form-group">
        <lavel>タイトル</lavel>
        {{ form.title }}
      </div>

      <!-- カテゴリーを追加 -->
      <div class="form-group">
        <lavel>カテゴリー</lavel>
        {{ form.category }}
      </div>
       <!-- サブカテゴリーを追加 -->
      <div class="form-group">
        <lavel>サブカテゴリー</lavel>
        {{ form.subcategory }}
      </div>
       <!-- サムネイルを追加 -->
      <div class="form-group">
        <lavel>サムネイル</lavel>
        {{ form.thumbnail }}
      </div>

      <br>
      <!-- 内容-->
      <div class = "form-group">
        <label>内容</label>
        {{ form.content}}
      <br>
      <br>
     <button type="submit" class="btn btn-light btn-rounded">保存</button>

    </form>
  </div>
</div>
{% endblock%}

blog_app/templates/blog_app/post_list.html
{%extends 'blog_app/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-9">
    <br>
    <h2>100story一覧</h2>
    <br>
    <table class="table">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>内容</th>
          <th>作成日時</th>
          <th>更新日時</th>
        </tr>
      </thead>
      <tbody>
        {%for item in post_list%}
        <tr>
           <td><a href="{% url 'blog_app:post_detail' item.pk %}">{{item.title}}</a></td>
           <td>{{item.content|safe|truncatechars_html:30}}</td>
           <td>{{item.created_at}}</td>
           <td>{{item.updated_at}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <br>
    <!-- ページネーション -->
    {% include 'blog_app/pagination.html'%}
    <!-- ページネーション -->
    <br>
  </div>
</div>
{% endblock%}

blog_app/templates/blog_app/search.html
{%extends 'blog_app/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-9">
    <br>
    <h2>100story一覧</h2>
    <br>
    <table class="table">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>内容</th>
          <th>作成日時</th>
          <th>更新日時</th>
        </tr>
      </thead>
      <tbody>
        {%for item in search_list%}
        <tr>
           <td><a href="{% url 'blog_app:post_detail' item.pk %}">{{item.title}}</a></td>
           <td>{{item.content}}</td>
           <td>{{item.created_at}}</td>
           <td>{{item.updated_at}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock%}

blog_app/templates/blog_app/signup.html
{%extends 'blog_app/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-6">
    <br>
    <h2>Sign up</h2>
    <br>

    <div class="card text-center">
      <div class="span3 well">
          <legend>New to 100story? Sign up!</legend>
          <form accept-charset="UTF-8" action="" method="post">
          {% csrf_token %}{{form.non_field_errors}}
            {% for field in form%}
                    <small>{{field.label}} </small>
                    <p class="span3">{{field}}<p>
                    {{ field.errors}}
                    <br>
            {% endfor%} 
            <button class="btn btn-warning" type="submit">Sign up for 100story</button>
          </form>
      </div>
    </div>

  </div>
{% endblock %}